# Generated by Django 4.0 on 2021-12-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес магазина')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('director', models.CharField(max_length=50, verbose_name='Руководитель')),
                ('e_mail', models.CharField(max_length=50, verbose_name='Почта')),
            ],
        ),
    ]
