# Generated by Django 4.0 on 2021-12-19 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_client_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(default=25, verbose_name='Цена')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='base.clients', verbose_name='Адрес магазина')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_supplier', to='base.suppliers', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('e_mail', models.CharField(max_length=30, verbose_name='Почта')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='base.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.clients')),
            ],
        ),
    ]
